prototype/urls.py
from django.urls import path, include

from .import views

app_name = 'prototype'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),

]

score/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static
from sense_i import settings
from .views import ChooseCreateView, TakeCreateView, ResultCreateView
from .views import ImageUpload


from .import views

app_name = 'score'
urlpatterns = [
    path('takepic', TakeCreateView.as_view(), name='take_pic'),
    path('choosepic', ChooseCreateView.as_view(), name='choose_pic'),
    path('result', ResultCreateView.as_view(), name='result'),
    path('imgupload', views.ImageUpload, name='imgupload'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sense_i/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prototype.urls')),
    path('score/', include('score.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prototype/models.py
from django.db import models

# Create your models here.

score/models.py
from django.db import models

# Create your models here.

class Image(models.Model):
   image = models.ImageField(default='default/default.png')

# 撮影した写真を送信する方

class TakePicture(models.Model):
    take_pic = models.ImageField(
        verbose_name = 'take_pic', upload_to = 'images/'
    )

# 選択した写真を送信する方

class ChoosePicture(models.Model):
    choose_pic = models.ImageField(
        verbose_name = 'choose_pic', upload_to = 'media/images/'
    )

class Result(models.Model):
    picture = models.ImageField(
        verbose_name = 'picture'
    )
    result = models.IntegerField(
        verbose_name = 'result'
    )

score/forms.py
from django import forms
from .models import TakePicture
from .models import ChoosePicture

class UploadFirst(forms.ModelForm):
    class Meta:
        model = TakePicture
        fields = ['take_pic']
    take_pic = forms.ImageField(required=True)

class UploadSecond(forms.Form):
    class Meta:
        model = ChoosePicture
        fields = ['choose_pic']
    choose_pic = forms.ImageField(required=True)

prototype/views.py
from django.shortcuts import render

# Create your views here.

from django.views import generic

class IndexView(generic.TemplateView):
    template_name = "prototype/index.html"

score/views.py
from django.shortcuts import render
from .models import Image
from django.http import HttpResponse
from .models import TakePicture, Result, ChoosePicture
from .forms import UploadFirst, UploadSecond
from django.views import generic
import base64
import cv2
import numpy as np
# Create your views here.

class TakeCreateView(generic.CreateView):
    model = TakePicture
    template_name = "score/take_pic.html"
    fields = '__all__'

    def edit_take_pic(request):
        if request.method != 'POST':
            form = UploadFirst()
        else:
            form = UploadFirst(request.POST, request.FILES)
            if form.is_valid():
                take_pic = form.cleaned_data['take_pic']
                take_picture = TakePicture()
                take_picture.take_pic = take_pic
                take_picture.save()

        context = {
            'form': form
        }
        return render(request, 'score/choose_pic.html', context)




class ChooseCreateView(generic.CreateView):
    model = ChoosePicture
    template_name = "score/choose_pic.html"
    fields = '__all__'

    def edit_choose_pic(request):
        if request.method != 'POST':
            form = UploadSecond()
        else:
            form = UploadSecond(request.POST, request.FILES)
            if form.is_valid():
                choose_pic = form.cleaned_data['choose_pic']
                choose_picture = ChoosePicture()
                choose_picture.choose_pic = choose_pic
                choose_picture.save()
                request.session['form_data'] = request.POST

        context = {
            'form': form
        }
        return render(request, 'score/choose_pic.html', context)

class ResultCreateView(generic.CreateView):
    model = Result
    template_name = "score/result.html"
    fields = '__all__'

def ImageUpload(request):
    if request.method == 'POST':
        print(list(request.POST.items()))
        print(dict(request.POST.items()))
        print(dict(request.FILES))
        posted_img = request.FILES['image']
        image = request.POST.get("image")
        image2 = dict(request.POST.items())["image"]
        new_image = Image.objects.create(image=posted_img)

        img_data = base64.b64decode(image)
        img_np = np.fromstring(img_data, np.uint8)
        src = cv2.imdecode(img_np, cv2.IMREAD_ANYCOLOR)

        print(src)

        return HttpResponse(new_image.image.url)

app/fashion-app/tango/app/templates/index.html
{% extends "bootstrap/base.html" %}

{% block title %}単語認識アプリ{% endblock %}

{% block content %}

{% if message %} 
<div class="alert alert-success" role="alert">{{ message }}<br></div>
{% endif %}

 <div style='background-image:"../img/img1.jpg;"'>
    <header class='masthead'>
        <div class='panel-in'>
            <div class='panel-bg'></div>
            <div class='panel-main'>
                <div class="container h-100 ">
                    <div class='row h-100 aligh-item-center justify-content-center text-center'>
                        <div class='col-lg-10 aligh-self-end'>
                            <h1 class='text-uppercase text-black font-weight-bold'>UPLOAD IMAGE</h1>
                        </div>
                    </div>
                </div>
                <div class='container h-100　'>
                    <div class='row h-100 aligh-item-center justify-content-center text-center'>
                        <div class='col-lg-10 aligh-self-end' display='flex'>
                            <h3 class='text-uppercase text-black'>画像を添付して単語帳を作ろう！</h3>
                            <a class="btn btn-primary" href="/result" role="button">単語テスト</a>
                        </div>
                    </div>
                </div>
        
                <div class='container h-100'>
                    <div class='row h-100 aligh-item-center justify-content-center text-center'>
                        <div class='col-lg-5 aligh-self-end'>
                            <div class="form-group">
                                <label for="inputFile">Image input</label>
                                <div class="custom-file">
                                    <form method="POST" action = "./" method = "POST" enctype = "multipart/form-data">
                                        <input type="file" class="custom-file-input" id="inputFile" name="file">
                                        <label class="custom-file-label" for="inputFile">Choose Image</label>
                                        <input type = "submit"/>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
    <script>
        bsCustomFileInput.init();
    </script>
</div>
{% endblock %}

app/fashion-app/tango/app/templates/result.html
{% extends "bootstrap/base.html" %}

{% block title %}自動単語帳作成アプリ{% endblock %}
   
{% block content %}

 <div class="container h-100 "style='margin:2rem 1rem 2rem;'>
  <a class="btn btn-primary" href="/" role="button" style='float:right'>単語登録</a>
  <div class='clumns text-center' style='display:flex; justify-content: space-around;'>
    <div class='col-lg-10 aligh-self-end'>
      {% for word,_ in dic.items() %}
      <div class="card border-success mb-3" style="max-width: 40rem; border-color: rgb(114, 108, 108); border-style: solid; border-width: 0.1rem;margin-bottom: auto;">
        <div class="card-header">{{"No."+loop.index|string}}</div>
        <div class="card-body text-success">
          <h2 class="card-title">{{ word }}</h2>
        </div>              
      </div>
      {% endfor %}
    </div>
    <div class='col-lg-10 aligh-self-end'>
      <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">和訳を表示</button>
      <div class="collapse" id="collapseExample">
        <div class="border p-3">
          {% for _,ans in dic.items() %}
          <div class="card border-success mb-3" style="max-width: 40rem; border-color: rgb(114, 108, 108); border-style: solid; border-width:0.1rem; margin-bottom: auto;">
            <div class="card-header">{{"No."+loop.index|string}}</div>
            <div class="card-body text-success">
              <h2 class="card-title">{{ ans }}</h2>
            </div>              
          </div>
          {% endfor %}
         </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

score/templates/score/take_pic.html
{% extends 'base_b.html' %}
{% load static %}

{% block header %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="{% static 'js/score.js' %}"></script>
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 justify-content-between">
        <div class="col-lg-5 my-auto align-self-start">
          <div class="header-content mx-auto">
            <h1 class="mb-5">シャッターを押し画像を撮ろう</h1>
              <video id="local_video" autoplay style="width: 667px; height:500px; border: 1px solid black;"></video>
              <form>
              <button type="button" id="shutter">シャッター</button>
              </form>
          </div>
        </div>
        <div class="col-lg-7 my-auto">
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block contents %}
  <section class="download bg-primary text-center" id="download">
    <div class="container h-100">
      <div class="row h-100 justify-content-between">
        <div class="col-lg-5 my-auto">
          <div class="header-content mx-auto">
            <h1 class="mb-5">撮れた画像を確認しよう</h1>
            <canvas id="canvas" style="width: 667px; height:500px; border: 1px solid black;"></canvas>
          </div>
          <img id="img">
          <form>
              {% csrf_token %}
              <button type="button" class="btn" id="send" formaction="{% url 'score:result' %}">採点</button>
          </form>
        </div>
          <div class="col-lg-7 my-auto">

          </div>
      </div>
    </div>
  </section>

  <section class="features" id="features">
    <div class="container">
      <div class="section-heading text-center">
        <h2>Unlimited Features, Unlimited Fun</h2>
        <p class="text-muted">Check out what you can do with this app theme!</p>
        <hr>
      </div>
      <div class="row">
        <div class="col-lg-4 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="{% static 'img/demo-screen-1.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 my-auto">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-screen-smartphone text-primary"></i>
                  <h3>Device Mockups</h3>
                  <p class="text-muted">Ready to use HTML/CSS device mockups, no Photoshop required!</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-camera text-primary"></i>
                  <h3>Flexible Use</h3>
                  <p class="text-muted">Put an image, video, animation, or anything else in the screen!</p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-present text-primary"></i>
                  <h3>Free to Use</h3>
                  <p class="text-muted">As always, this theme is free to download and use for any purpose!</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-lock-open text-primary"></i>
                  <h3>Open Source</h3>
                  <p class="text-muted">Since this theme is MIT licensed, you can use it commercially!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="cta">
    <div class="cta-content">
      <div class="container">
        <h2>Stop waiting.<br>Start building.</h2>
        <a href="#contact" class="btn btn-outline btn-xl js-scroll-trigger">Let's Get Started!</a>
      </div>
    </div>
    <div class="overlay"></div>
  </section>

  <section class="contact bg-primary" id="contact">
    <div class="container">
      <h2>We
        <i class="fas fa-heart"></i>
        new friends!</h2>
      <ul class="list-inline list-social">
        <li class="list-inline-item social-twitter">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="list-inline-item social-facebook">
          <a href="#">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="list-inline-item social-google-plus">
          <a href="#">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
      </ul>
    </div>
  </section>
{% endblock %}

sense_i/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
{#ホーム画面用のHTML#}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ファッションAI - Sense-i</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

  <!-- Plugin CSS -->
  <link rel="stylesheet" href="{% static 'device-mockups/device-mockups.min.css' %}">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/new-age.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'prototype:index' %}">Sense-i</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            {% block navigation %}{% endblock %}
        </ul>
      </div>
    </div>
  </nav>

  {% block header %}{% endblock %}

  {% block main_contents %}{% endblock %}



    <section class="features" id="features">
    <div class="container">
      <div class="section-heading text-center">
        <h2>Let's become FASHION MASTER</h2>
        <p class="text-muted">ファッションマスターを目指そう！</p>
        <hr>
      </div>
      <div class="row">
        <div class="col-lg-4 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="{% static 'img/demo-screen-1.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 my-auto">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-screen-smartphone text-primary"></i>
                  <h3>AIがあなたの服装を採点</h3>
                  <p class="text-muted">写真を撮影、またはアップロードするだけ！すぐにAIが採点してくれます。</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-camera text-primary"></i>
                  <h3>採点結果をSNSでシェア</h3>
                  <p class="text-muted">採点結果をTwitter、Instagram、Facebookで共有しよう！</p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-present text-primary"></i>
                  <h3>完全無料</h3>
                  <p class="text-muted">AI採点は何度使っても無料！色んな服装を試してみよう！</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-lock-open text-primary"></i>
                  <h3>ランキング機能も実装予定！</h3>
                  <p class="text-muted">日本一のファッションマスターに輝くのは誰だ！</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="download bg-primary text-center" id="download">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <h2 class="section-heading">Join Beta</h2>
          <p>Android・iOSにてベータ版、近日登場</p>
          <div class="badges">
            <a class="badge-link" href="#"><img src="{% static 'img/google-play-badge.svg' %}" alt="" style="opacity: 0.5;"></a>
            <a class="badge-link" href="#"><img src="{% static 'img/app-store-badge.svg' %}" alt="" style="opacity: 0.5;"></a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="cta">
    <div class="cta-content">
      <div class="container">
        <h2>Please<br>help us</h2>
        <a href="#contact" class="btn btn-outline btn-xl js-scroll-trigger">アドバイスを送る</a>
      </div>
    </div>
    <div class="overlay"></div>
  </section>

  <section class="contact bg-primary" id="contact">
    <div class="container">
      <h2>We
        <i class="fas fa-heart"></i>
        new friends!</h2>
      <ul class="list-inline list-social">
        <li class="list-inline-item social-twitter">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="list-inline-item social-facebook">
          <a href="#">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="list-inline-item social-google-plus">
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
        </li>
      </ul>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; Sense-i Development Team 2021. All Rights Reserved.</p>
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a href="#">Terms</a>
        </li>
        <li class="list-inline-item">
          <a href="#">FAQ</a>
        </li>
      </ul>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/new-age.min.js' %}"></script>

</body>

</html>

sense_i/templates/prototype/index.html
{% extends 'base.html' %}
{% load static %}


{% block navigation %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#features">Features</a>
    </li>
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#download">BETA</a>
    </li>
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
    </li>
{% endblock %}



{% block header %}
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <h1 class="mb-5">Sense-i へようこそ！</h1>
            <form>
                <small>＊写真に映るものが人ではない場合や、対象の人以外に映り込む物が多すぎるとうまく採点されないことがあります</small>
            </form>
            <div class="dropdown">
                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    採点する
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a href="{% url 'score:take_pic' %}" class="dropdown-item">撮影して採点してもらう</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'score:choose_pic' %}" class="dropdown-item">持ってる画像を採点してもらう</a></li>
                </ul>
            </div>
            <a href="{% url 'score:result' %}" class="btn btn-outline btn-xl js-scroll-trigger dropdown-item">結果</a>
          </div>
        </div>
        <div class="col-lg-5 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="{% static 'img/demo-screen-1.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_contents %}{% endblock %}

sense_i/templates/score/choose_pic.html
{% extends 'base.html' %}
{% load static %}


{% block navigation %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{% url 'prototype:index' %}">トップページ</a>
    </li>
{% endblock %}


{% block header %}
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <h1 class="mb-5">画像を選んでね</h1>
              <form action="" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
　    　　　　　　　{{ form.choose_pic }}
    　　　　　　　　<button type="submit" class="btn" formaction="{% url 'score:result' %}">採点スタート！！</button>
    　　　　　　</form>
          </div>
        </div>
        <div class="col-lg-5 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="{% static 'img/demo-screen-1.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_contents %}{% endblock %}

sense_i/templates/score/result.html
{% extends 'base.html' %}
{% load static %}


{% block navigation %}{% endblock %}


{% block header %}
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 justify-content-center">
        <div class="col-lg-5 my-auto">
            <div class="header-content mx-auto">
              <div class="card bg-warning" style="max-width:200rem">
                  <div class="card-header">
                      <h4>採点結果</h4>
                  </div>
                  <img class="card-img-top" src="{% static 'img/サンプルパイナップル.jpg' %}" alt="">
                  <div class="card-body">
                      <p>結果を共有する</p>
                      <div class="dropdown">
                        <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          もう一度採点する
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <li><a href="{% url 'score:take_pic' %}" class="dropdown-item">撮影して採点してもらう</a></li>
                            <li role="separator" class="divider"></li>
                          <li><a href="{% url 'score:choose_pic' %}" class="dropdown-item">持ってる画像を採点してもらう</a></li>
                        </ul>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        <div class="col-lg-5 my-auto">
            <div class="header-content mx-auto">
              <div class="card bg-info" style="max-width:200rem">
                  <div class="card-header">
                      <h2>点数</h2>
                  </div>
                  <div class="card-body">
                      <h1>100点</h1>
                  </div>
              </div>
                <div>
                <div class="card bg-info" style="max-width:200rem">
                  <div class="card-header">
                      <h2>コメント</h2>
                  </div>
                  <div class="card-body">
                      <h2>美味しそう（ﾆﾁｬ）</h2>
                  </div>
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
                       data-size="large"
                       data-text="ファッション採点AI&quot;Sense-i&quot;での採点結果は・・・{{ result }}点でした！"
                       data-url="https://www.instagram.com/h.takahira0205/?hl=ja"
                       data-hashtags="ファッションAI,sense_i"
                       data-related="h_takahira_fst" data-show-count="false">
                        Tweet
                    </a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_contents %}{% endblock %}

sense_i/templates/score/take_pic.html
{% extends 'base.html' %}
{% load static %}


{% block navigation %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{% url 'prototype:index' %}">トップページ</a>
    </li>
{% endblock %}


{% block header %}
  <script src="{% static 'js/score.js' %}"></script>
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 justify-content-between">
        <div class="col-lg-5 my-auto align-self-start">
          <div class="header-content mx-auto">
            <h1 class="mb-5">シャッターを押し画像を撮ろう</h1>
              <video id="local_video" autoplay style="width: 667px; height:500px; border: 1px solid black;"></video>
              <form>
              <button type="button" id="shutter">シャッター</button>
              </form>
          </div>
        </div>
        <div class="col-lg-7 my-auto">
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block main_contents %}
  <section class="download bg-primary text-center" id="download">
    <div class="container h-100">
      <div class="row h-100 justify-content-between">
        <div class="col-lg-5 my-auto">
          <div class="header-content mx-auto">
            <h1 class="mb-5">撮れた画像を確認しよう</h1>
            <canvas id="canvas" style="width: 667px; height:500px; border: 1px solid black;"></canvas>
          </div>
          <form>
              <button type="button" id="send">採点</button>
          </form>
        </div>
          <div class="col-lg-7 my-auto">

          </div>
      </div>
    </div>
  </section>
{% endblock %}